Myproject/Customer/urls.py
from django.urls import path
from Customer import views
app_name='Customer'

urlpatterns = [

    path('',views.web2,name='web2'),
    path('web2/ordernow/',views.orderNow,name='orderNow'),
    path('web2/ordernow/zomato/',views.zomato,name='zomato'),
]

Myproject/Myproject/urls.py
from django.contrib import admin
from django.urls import path,include
# from foodapp import views
# from foodapp.views import HttpResponse
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/',include('foodapp.urls')),
    path('users/',include('users.urls')),
    path('login/',views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('web2/',include('Customer.urls')),
]
urlpatterns +=[]+ static(settings.MEDIA_ROOT, document_root=settings.MEDIA_ROOT)

Myproject/foodapp/urls.py
from django.urls import path
from foodapp import views
app_name='foodapp'

urlpatterns = [
    path('',views.index,name='index'),
    path('<int:id>/',views.detail,name='detail'),
    
    # path('home/',views.food,name='food'),
    path('add/',views.create_item,name='create_item'),
    # path('web2/',views.web2,name="web2"),
    path('update/<int:id>/',views.update,name='update'),
    path('delete_item/<int:id>/',views.delete_item,name='delete_item'),
    
]

Myproject/users/urls.py
from django.urls import path

from . import views
app_name='users'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('success/',views.success,name='success'),
    path('profile/',views.profile,name='profile'),

]

Myproject/Customer/models.py
from django.db import models
from django.db import connections

# Create your models here.
class Order(models.Model):
    uname=models.CharField(max_length=122)
    date=models.DateField(null=True)
    email=models.CharField(max_length=122)
    number=models.BigIntegerField()
    food=models.CharField(max_length=122)
    Restaurant=models.CharField(max_length=122)
    drinks=models.CharField(max_length=122)
    soups=models.CharField(max_length=122)
    dish=models.CharField(max_length=122)
    order=models.CharField(max_length=122)

Myproject/foodapp/models.py
from django.db import models
from django.db import connections
# Create your models here.

class Item(models.Model):
    item_name=models.CharField(max_length=122)
    item_desc=models.CharField(max_length=122)
    item_price=models.IntegerField()
    item_image=models.ImageField(max_length=5000,default='https://as2.ftcdn.net/v2/jpg/02/88/85/71/1000_F_288857162_l7ZOOsEveQf1d8PMsNC6HMQFeqafLJhx.jpg')

    def __str__(self):
        return self.item_name
    
class Contact2(models.Model):
    name2=models.CharField(max_length=122)
    email2=models.CharField(max_length=122)
    phone2=models.CharField(max_length=12)

Myproject/users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Profile(models.Model):
    user_instance=models.OneToOneField(User,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='profile_images',default='profile.jpg')

Myproject/Customer/forms.py
from django import forms
from .models import Order
class OrderForms(forms.ModelForm):
    class Meta:
        model=Order
        fields=['uname','date','email','number','food','Restaurant','drinks','soups','dish','order']

Myproject/foodapp/forms.py
from django import forms
from .models import Item

class ItemForms(forms.ModelForm):
    class Meta:
        model=Item
        fields=['item_name','item_desc','item_price','item_image']

Myproject/Customer/views.py
from django.shortcuts import render
from Customer.models import Order
from Customer.forms import OrderForms
# Create your views here.

def web2(request):
    # template=loader.get_template('web2.html')
    return render(request,'Customer/web2.html')
def orderNow(request):
    return render(request,'Customer/zomato.html')
def zomato(request):
    if request.methods=='post':
        uname=request.POST.get('uname')
        date=request.POST.get('date')
        email=request.POST.get('email')
        number=request.POST.get('number')
        food=request.POST.get('food')
        Restaurant=request.POST.get('Restaurant')
        drinks=request.POST.get('drinks')
        soups=request.POST.get('soups')
        dish=request.POST.get('dish')
        order=request.POST.get('order')
        zomato=Order(uname=uname,date=date,email=email,number=number,food=food,Restaurant=Restaurant,drinks=drinks,soups=soups,dish=dish,order=order)
        zomato.save()
    return render(request,'zomato.html')

Myproject/foodapp/views.py
from django import template
from django.shortcuts import render,redirect
from django.template import loader
from foodapp.models import Contact2
# from django.http import HttpResponse
from foodapp.models import Item
from .forms import ItemForms
from django.contrib.auth.decorators import login_required

# Create your views here.
# def home(request):
#     return HttpResponse("Hello in my project's home page")
@login_required
def index(request):
    item_list=Item.objects.all()
    context={
        'item_list':item_list,
    }
    return render(request,"index.html",context)

def detail(request,id):
    item=Item.objects.get(pk=id)
    context={
        'item':item,
    }
    return render(request,"detail.html",context)

def create_item(request):
    form=ItemForms(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('foodapp:index')
    return render(request,'item-form.html',{'form':form})

def update(request,id):
    item=Item.objects.get(id=id)
    form=ItemForms(request.POST or None,instance=item)
    if form.is_valid():
        form.save()
        return redirect('foodapp:index')
    return render(request,'item-form.html',{'form':form})

def delete_item(request,id):
    item=Item.objects.get(id=id)
    if request.method=='POST':
        item.delete()
        return redirect('foodapp:index')
    return render(request,'delete_msg.html',{'item.item_name':item.item_name})

Myproject/users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
# from django.contrib.auth.decorators import login_required
# Create your views here.
def register(request):
    form=UserCreationForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('users:success')
    return render(request,'users/register.html',{'form':form})

def success(request):
    return render(request,'users/logout.html')

# def login(request):
#     return render(request,'users/login.html')
# def logout(request):
#     return render(request,'users/logout.html')
def profile(request):
    profile_instances=Profile.objects.all()
    context={
        'profile_instances':profile_instances
    }
    return render(request,'users/profile.html',context)
    

Myproject/Customer/templates/Customer/web2.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bhojan</title>
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" media="screen and (max-width: 1250px)" href="phone.css">
    <link href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans:wght@700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <style>
     

.two{font-size: 30px;
    text-decoration: none;
    color: whitesmoke;
    
}

*{
    padding: 0; margin: 0; box-sizing: border-box;
}

html{
    
    scroll-behavior: smooth;
    font-family: 'Balsamiq Sans', cursive;
}

#head-container{
    display: flex;
    width: 100%;
    /* border: 2px dotted black; */
    background-color: rgb(204, 87, 18);
    padding: 10px 0 10px 0;
    position: sticky;
    top: 0;
    z-index: 10;
}

#head-container .logo{
    /* border: 2px dotted red; */
    width: 10%; 
    /* flex-grow: 1; */
}

#head-container .logo img{
    display: block;
    width: auto;
    margin: auto;
    height: 5rem;
}

#head-container nav{
    /* border: 2px dotted red; */
    width: 70%; 
    /* flex-grow: 4;  */
}

#head-container nav ul{
    display: flex;
    margin-top: 18px;
    flex-wrap: wrap;
    /* margin-left: 1rem; */
}

#head-container nav ul li{
    list-style: none;
    /* flex-grow: 1; */
    padding: 0 1rem 0 1rem;
    font-size: 2rem;   
}

#head-container nav ul li a{
    text-decoration: none;
    color: white;
    padding: 0 15px;
}

#head-container nav ul li a:hover{        
    background-color: white;
    color: black;
    border-radius: 25px;
}

#search{
    /* border: 2px dotted red; */
    /* flex-grow: 1.5; */
    width: 20%;
}

#search input{
    width: 80%;
    text-align: center;
    margin: 20px 0 0 0;
    height: 2rem;
    border-radius: 20px;
    font-size: medium;
}

#main{
    /* border: 2px dotted black; */
    background-image: url(bg1.jpg);
    background-size: cover;
    background-position: center;
    background-repeat: no-repeat;
    position: relative;
    width: 100%;
    height: 90vh;
    color: white;

}

.main_container{
    /* border: 2px dotted red;   */
    display: flex; 
    flex-direction: column; 
    align-items: center;
    position: absolute;
    z-index: 2;
    top: 10rem;
}

#main h6{
    text-align: center;
    font-size: 5rem;
}

#main p{
    text-align: center;
    font-size: 2rem;
    margin: 4rem 3rem 0 3rem;
}

.btn{
    background-color: rgb(165, 31, 31);
    font-size: 2rem;
    border: 2px solid white;
    color: white;
    border-radius: 20px;
    width: 20%;
    margin-top: 5rem;
    cursor: pointer;
}
#orderNow{
    background-color: rgb(205, 193, 193);
    align-items: center;
    text-align: center;
    padding: 20px;
    margin-left: 250px;
    border-radius: 20px;
    opacity: 70%;
    color: black;
}

h1{
    text-align: center;
    margin-top: 1.5rem;
    font-size: 3rem;
}


#client{
    /* border: 2px dotted black; */
    background-image: url('../img/bg.jpg');
    background-size: cover;
    background-position: center;
    background-repeat: no-repeat;
    position: relative;
    width: 100%;
    height: 350px;
}

.overlay{
    background-color: #000000a8;
    color: white;
    position: absolute;
    top:0;
    left: 0;
    right: 0;
    bottom: 0;
    z-index: 1;
}

.client_container{
    /* border: 2px dotted black; */
    position: absolute;
    z-index: 2;
    display: flex;
    top: 4rem;
    left:10%;
    right: 10%;
}



#client .box{
    /* border: 2px dotted red; */
    padding: 0 2rem;
    margin: 2rem 2rem 2rem 2rem;
}

#client .box img{
    width: 10rem;
    height: 10rem;
}

#contact{
    /* border: 2px dotted black; */
    background-image: url('https://media.istockphoto.com/id/1311934969/photo/contact-us.jpg?b=1&s=170667a&w=0&k=20&c=2sJEN1Hhg6heUi1ZxKs6pJDwcyLYXPc4pUGd3hEjOjE=');
    background-size: cover;
    background-position: center;
    background-repeat: no-repeat;
    padding: 1rem 0;
}

#contact form{
    /* border: 2px dotted red; */
    width: 50%;
    margin: 1rem auto;
    /* margin-bottom: 1rem; */

}

#contact form label,textarea,input{
    display: block;
    width: 100%;
    font-size: 1.5rem;
}

#contact form input{
    border-radius: 0.8rem;
    margin-bottom: 1rem;
}

#contact form textarea{
    border-radius: 0.8rem;
}

footer{
    background-color: black;
    color: white;
    padding: 1rem 0;
}

footer div{
    text-align: center;
}

#head-container{
    flex-direction: column;
    align-items: center;
    position: static;
}

#head-container .logo{
    width: 100%;
}

#head-container nav{
    width: 100%; 
    
}

#head-container nav ul{
    justify-content: center;
}

#search {
    width: 100%
}

#search input{
    margin:20px 20px 0 20px;
    width: 60%;
    margin: 20px auto 0 auto;
}

#main{
    height: 445px;
}

.main_container{
    top: 3rem;
}

#main h6{
    font-size: 2rem;

}

#main p{
    font-size: 1rem;
    margin-top: 3rem;
}

.btn{
    font-size: 1rem;
    width: 30%;
    height: 40px;
    margin-top: 3rem;
}


#services{
    flex-direction: column;
    /* margin: auto; */
    /* justify-content: center; */
}

#services .box{
    width: 90%;
    margin: 1rem auto;
}

.client_container{
    overflow: scroll;
}

#contact form{
    width: 90%;
}

    </style>
</head>

<body>
    <header id="head-container">
        <div class="logo">
    <img src="https://img.freepik.com/premium-vector/gold-healthy-food-icon-vector-illustration-two-forks-heart-shape_118339-1069.jpg?w=2000" alt="Logo">
        </div>
        <nav>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#scroll_services">Service</a></li>
                <li><a href="#scroll_clients">Clients</a></li>
                <li><a href="#scroll_contact">Contact</a></li>
                <li><a href="#">About Us</a></li>
            </ul>
        </nav>
        <div id="search">
            <input type="text" name="search" placeholder="Search">
        </div>
    </header>
    <div id="main">
        <div class="overlay"></div>
        <div class="main_container">
            <h6 style=padding-left:250px>Welcome to Khana khajana</h6>
            <p style="padding-left:200px">Food brings people together on many different levels. It’s nourishment of the soul and body; it’s truly love.</p>
       
            <br><br>
            
    <button class="two" id="orderNow" name="orderNow">Order Now</button>
    
            
            
        </div>

    </div>
    <h1 id="scroll_services">Our Services</h1>
    <div id="services">
        <div class="box" data-aos="fade-left">
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIww3ydX26Nfun5iXxfZVYJ_kgYU27YN-2JbO-k52OTEH7o3ZN1POZZtujL7i5DDcJLxI&usqp=CAU" alt="">
            <h2>Food Catering</h2>
            <p>Food catering is always an essential ingredient for any party, corporate event, wedding event, family reunions or baby showers. When your guests attend your event, they will expect to be served with delicious and good food.</p>
        </div>
        <div class="box" data-aos="fade-down">
            <img src="https://www.decornt.com/images/bulk_order.png" alt=""  height="200px" width="300px">
            <h2>Bulk Ordering</h2>
            <p>Food catering is always an essential ingredient for any party, corporate event, wedding event, family reunions or baby showers. When your guests attend your event, they will expect to be served with delicious and good food.</p>
        </div>
        <div class="box" data-aos="fade-right">
            <img src="https://thumbs.dreamstime.com/b/food-delivery-man-delivering-food-scooter-food-delivery-man-delivering-food-scooter-isolated-white-background-176181732.jpg" alt="" height="200px" width="300px">
            <h2>Food Ordering</h2>
            <p>Food catering is always an essential ingredient for any party, corporate event, wedding event, family reunions or baby showers. When your guests attend your event, they will expect to be served with delicious and good food.</p>
        </div>
    </div>
    <h1 id="scroll_clients">Our Clients</h1>
    <div id="client">
        <div class="overlay"></div>
        <div class="client_container">
            <div class="box">
                <a href="https://www.zomato.com/" target="_blank"><img src="https://upload.wikimedia.org/wikipedia/commons/7/75/Zomato_logo.png" alt="clients"></a>

            </div>
            <div class="box">
                <a href="https://www.foodpanda.com/" target="_blank"><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdtb-XID0x4c1YolP7S4GLLJvnQlHLhWM1cwBmWF_qa_yGrc4CJfXbi3QcBP6Ra7TvUjM&usqp=CAU" alt="clients"></a>

            </div>
            <div class="box">
                <a href="https://www.swiggy.com/" target="_blank"><img src="https://st.adda247.com/https://wpassets.adda247.com/wp-content/uploads/multisite/sites/5/2022/05/16165408/swiggy.jpeg" alt="clients"></a>

            </div>
            <div class="box">
                <a href="https://www.ubereats.com/" target="_blank"><img src="https://seeklogo.com/images/U/uber-eats-logo-65D72FAA4C-seeklogo.com.png" alt="clients"></a>
            </div>

        </div>

    </div>
    <h1 id="scroll_contact" style="font-size: 30px;font-size: 50px;">Contact</h1>
    <div id="contact">
        <form method="post" action="">
            {% csrf_token %}

            <label for="name" style="color:whitesmoke">Name:</label>
            <input type="text" id="name2" name="name2" placeholder="Enter your name" patter="[a-zA-Z]{3,30}">
            <label for="email" style="color:whitesmoke">Email:</label>
            <input type="email" id="email2" name="email2" placeholder="Enter your email" pattern="[a-zA-Z0-9$%&*]+@[a-z]+.[a-z]{3,10}" title="Invalid Email...!!">
            <label for="phone" style="color:whitesmoke">Phone Number:</label>
            <input type="phone" id="phone2" name="phone2" placeholder="Enter your phone" pattern="^[6-9]{1}[0-9]{9}$" title="Enter valid Phone_number">
            
            <br><br>
            <button type="submit" class="btn btn-primary" class="center" >SUBMIT</button>
        </form>
    
    </div>
    <footer>
        <div>
            Copyright © www.bhojan.com. All rights reserved!
        </div>
    </footer>
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
        AOS.init({
            offset: 180,
            duration: 1500
        });
    document.getElementById("orderNow").onclick = function () {
        location.href = "./ordernow/";
    };
    </script>
</body>
</html>

Myproject/Customer/templates/Customer/zomato.html
<!-- Code by technoniit  -->

<!Doctype html>
<html>
<head>
    
   <title>Tomato</title>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap Code -->
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <!-- Bootstrap code end -->
 
    <!-- CSS Code -->
   <style>
body{background-image: url("https://img.freepik.com/free-photo/vegetables-set-left-black-slate_1220-685.jpg?size=626&ext=jpg&ga=GA1.2.1821626773.1677157478&semt=sph");
background-repeat: no-repeat;
background-size: cover;}
   div#a
 {
 background-color:red;
 font-family: cursive;
 opacity:0.7;
 width:400px;
 height:630px;
 color:black;
 border-radius:70px;  
 }
     h1
 {
 color:black;
 }
     table td
 {
  padding-top:6px;
 } 
   </style>
    <!-- CSS Code End -->
  
</head>
<body>
<center>
<div id="a" class="container">
<form method="post" action="" class="form-horizontal">
    {% csrf_token %}
<h1 id="zomato">
Order Here</h1>
<div class="form-group">
<table>
<tr>
 <td>Name:</td>
 <td><input type="text" placeholder="Example" name="uname" id="uname" required class="form-control"></td>
 </tr>
<tr>
 <td>Date:</td>
 <td><input type="Date" name="date" id="date" required class="form-control"></td>
 </tr>
<tr>
 <td>Email:</td>
 <td><input type="email" placeholder="Example@gmail.com" name="email" id="email" required class="form-control"></td>
 </tr>
<tr>
 <td>Contact Number:</td>
 <td><input type="number" placeholder="1234567890" name="number" id="number" required class="form-control"></td>
 </tr>
<tr>
 <td>Select Food:</td>
 <td><input name="food" type="radio" checked value="Non-Vegetation" required>Non-Vegetation
     <input name="food" type="radio" value="Vegetation" required >Vegetation</td>
 </tr>
<tr>
 <td><label for="restro">Select Restaurant:</label></td>
 <td><select class="form-control" id="Restaurant" name="Restaurant">
  <option>Select your Restaurant</option>
  <option value="Mahek Restaurant">Mahek Restaurant</option>
  <option value="Janta Restaurant">Janta Restaurant</option>
  <option value="Galaxy Restaurant">Galaxy Restaurant</option>
  <option value="Brijwasi Restaurant" >Brijwasi Restaurant</option>
 </Select></td>
 </tr>
<tr>
    
 <td><label for="Drinks">Drinks:</label></td>
 <td><select class="form-control" id="drinks" name="drinks">
  <option value="select">Select your Drinks</option>
  <option value="Cappuccino">Cappuccino</option>
  <option value="Caffelatte">Caffelatte</option>
  <option value="Cold drinks">Cold Drinks</option>
 </Select></td>
 </tr>
<tr>
 <td><label for="soups">Soups:</label></td>
 <td><select class="form-control" id="soups" name="soups">
         <option value="opt10">Select the Soups of your choice</option>
  <option value="Tomato Soup">Tomato Soup</option>
  <option value="MineStronw" >MineStronw</opteon>
  <option value="Fonduta">Fonduta</option>
  <option value="pasta">Pasta e fagioli</option>
 </Select></td>
 </tr>
<tr>
 <td><label for="dishes">Dishes:</label></td>
 <td><select class="form-control" id="dish" name="dish">
  <option>Select the dishes of your choice</option>
  <option value="Pasta">Pasta</option>
  <option value="Rice">Rice</option>
  <option value="Half-plate">Half-plate</option>
  <option value="Full-Plate">Full-Plate</option>
 </Select></td>
 </tr>
<tr>
 <td>Order For:</td>
 <td><input name="order" type="radio"  value="Take Away" required id="take" name="take">Take Awqay
     <input name="order" type="radio" value="Home Delivery" required id="homed" name="homed">Home Delivery</td>
 </tr>


<tr>
 <td><button value="btn" class="btn btn-primary btn-block">Order Now</button></td>
 <td style="padding-left:50px;"><button value="btn1" type="reset" class="btn btn-primary btn-block">Reset</button></td>
 </tr>
</table>
</div>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
</form>
</div>
</center>
</body>
</html>

Myproject/foodapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'foodapp/style.css' %}">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <style>
      #logout-button{
        border: none;
        color: rgb(92, 92, 224);
        padding-top: 15px;
        background-color: white;
      }
    </style>

</head>
<body>
    <div class="container-fluid">

        <div class="navbar-header">

          <a class="navbar-brand" href="{% url 'foodapp:index' %}" style='font-weight:bold'>FoodApp</a>

        </div>

        <ul class="nav navbar-nav">

          <li class="active"><a href="{% url 'users:profile' %}">Profile</a></li>

          <li><form action="{% url 'logout' %}" method="post">
            {% csrf_token %} 
            <button type="submit" id="logout-button">Logout</button>
        </form></li>

          <!-- <li><a href="{% url 'logout' %}">Logout</a></li> -->

          <!-- <li><a href="#">Login</a></li> -->

        </ul>

      </div>

    </nav>
    {% block body %}
    {% endblock %}
</body>
</html>

Myproject/foodapp/templates/delete_msg.html
{% extends 'base.html' %}
{% block body %}
<form method="post">
    {% csrf_token %}
    <h2>Are you sure to delete {{item.item_name}}</h2>
    <button>Yes</button>
</form>
{% endblock %}

Myproject/foodapp/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-4">
        <img src="{{item.item_image}}">
    </div>
    <div class="col-md-2">
        <h2>{{ item.item_name }}</h2>
    </div>
    <div class="col-md-2">
        {{ item.item_desc }}
    </div>
    <div class="col-md-2">
        <br>
        <a href="{% url 'foodapp:create_item' %}" class="btn btn-success">Add Item</a>
        <br><br>
        <a href="{% url 'foodapp:update' item.id %}" class="btn btn-success">Upadate</a>
        <br><br>
        <a href="{% url 'foodapp:delete_item' item.id %}" class="btn btn-success">Delete</a>
    </div>
</div>

{% endblock %}

Myproject/foodapp/templates/index.html
{% extends 'base.html'%}
    {% block body %}
    {% for item in item_list %}
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-4">
            <img src="{{item.item_image}}" alt="">
        </div>
        <div class="col-md-2">
             {{ item.item_name }}
        </div>
        
        <div class="col-md-3">
        <a href="{% url 'foodapp:detail' item.id %}" class="btn btn-success">Details</a>
        </div>
        </div>
        <br><hr><br>
    {% endfor %}
    {% endblock %}
</body>
</html>

Myproject/users/templates/users/logout.html
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'foodapp/style.css' %}">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

</head>
<body>
    <div class="container-fluid">

        <div class="navbar-header">

          <a class="navbar-brand" href="{% url 'foodapp:index' %}" style='font-weight:bold'>FoodApp</a>

        </div>

        <ul class="nav navbar-nav">

          <li class="active"><a href="{% url 'users:profile' %}">Profile</a></li>

          

          <li><a href="{% url 'login' %}">Login</a></li>

          <!-- <li><a href="#">Login</a></li> -->

        </ul>

      </div>

    </nav>
    <div class="message-container">
        <h3>You've been Successfully Logged Out. </h3>
            <h4>See You Next Time!</h4>
    </div>
    
    {% endblock %}
    
</body>
</html>

Myproject/users/templates/users/register.html
<!-- <form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">Register</button>
</form> -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Registration</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }
        .container {
            max-width: 400px;
            margin: 50px auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h2 {
            text-align: center;
            margin-bottom: 20px;
        }
        form {
            display: flex;
            flex-direction: column;
        }
        label {
            margin-bottom: 8px;
            font-weight: bold;
        }
        input[type="text"], input[type="email"], input[type="password"] {
            padding: 8px;
            margin-bottom: 16px;
            border: 1px solid #ccc;
            border-radius: 4px;
            font-size: 14px;
        }
        button[type="submit"] {
            background-color: #007bff;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
            transition: background-color 0.3s ease;
        }
        button[type="submit"]:hover {
            background-color: #0056b3;
        }
    </style></head><body>
    <div class="container">
        <h2>User Registration</h2>
        <form method="post">
            {% csrf_token %}
            <label for="id_username">Username:</label>
            {{ form.username }}          
            <!-- <label for="id_email">Email:</label>
            {{ form.email }}  -->
            <label for="id_password1">Password:</label>
            {{ form.password1 }} 
            <label for="id_password2">Confirm Password:</label>
            {{ form.password2 }}
            <button type="submit">Create User</button>
        </form></div></body></html>